name: Learn basics of GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  helloworld:
    runs-on: ubuntu-latest
    container:
     image : alpine:latest
  
    steps:
      - name: print hello
        run: cat /etc/os-release
        
     
